This notebook is part the of Dr. Christoforos Christoforou's course materials. You may not, nor may you knowingly allow others to reproduce or distribute lecture notes, course materials or any of their derivatives without the instructor's express written consent.

In [6]:
# Setting up the environment  
import tensorflow.keras 
from tensorflow.keras.callbacks import EarlyStopping 
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.datasets import mnist 
from tensorflow.keras import backend

%matplotlib inline 
import matplotlib.pyplot as plt
import numpy as np 
import pandas as pd

## Exercise 1: Load and preprocess the dataset.

**Task 1: Load the MNIST dataset**: In the cell below, load the MNIST dataset, and standardize the dataset by applying the following pre-processing steps:

- Reshape the data array to `channels_last` (i.e. `(obs,row,cols,color)`).
- Convert the data array to `float32`.
- Normalize data array (i.e. divide by 255)
- Convert labels to categorical variables (i.e. one-hot encoding) using the `tensorflow.keras.utils.to_categorical(y_train)`.

At the completion of this step you should have the following variables:
Shape X_train : (60000, 28, 28, 1)
Shape y_train : (60000, 10)
Shape X_test : (10000, 28, 28, 1)
Shape y_test : (10000, 10)

* `X_train`,`X_test`: 4D array of shape (60000, 28, 28, 1) and (10000, 28, 28, 1) respectively, that stores the standardized MNIST data.
* `y_train` and `y_test`: 2D array of shape (60000, 10) and (10000, 10) which uses one-hot-encoding for the labels in the MNIST dataset.




In [9]:
# Setting up the environment  
import tensorflow.keras 
from tensorflow.keras.callbacks import EarlyStopping 
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.datasets import mnist 
from tensorflow.keras import backend

%matplotlib inline 
import matplotlib.pyplot as plt
import numpy as np 
import pandas as pd

(X_train, y_train),(X_test, y_test) = tensorflow.keras.datasets.mnist.load_data()

(Nobs_train, n_rows, n_cols) = X_train.shape

X_train = X_train.reshape(Nobs_train,n_rows,n_cols,1).astype('float32')/255

y_train = tensorflow.keras.utils.to_categorical(y_train)

11493376/11490434 [==============================] - 0s 0us/step


## Exercise 2:Building a Convolutional Neural Network using high-level Keras API

In this introductory example, we will build a convolutional neural network using high-level Keras API. For that, you will need several objects provided by the API;which include the `Sequential` model which is defined under the module `tensorflow.keras.models`, and four computational layers that are defined under the `tensorflow.keras.layers module`. These layers include 

* the `Conv2D` layer which implement the convolutional layer;
* the `MaxPool2D` layer which implements the max pooling operation;
* the `Flatten` layer and the `Dense` layer

These libraries have been imported at the beginning of the notebook, but to make this section self-contained, we re-import them in the cell below.


In [10]:
import tensorflow.keras 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPool2D, Dropout
import time

**Defining a CNN Architecture**

We can define the convolutional neural network architecture using the keras API. First, we define a general `Sequential` model and then `add` to it the various computational layer.

**Convolutional layer:** The first layer of the model will be a convolutional layer defined by the `Conv2D` layer in keras. The `Conv2D` layer takes several parameters, but in this example, we will focus on the two required parameters; these are the `filters` and the `kernel_size`. The `filters` argument is an integer that specifies the number of filters (i.e. kernels) to use used during the cross-correlation (we can think of this parameter as the size of the filter bank we want to use). The `kernel_size` parameters, is a tuple that specifies the kernel size to use. For example, the code `Conv2D(filters=32, kernel_size=(3,3))` specifies a convolutional layer that uses 32 filters/kernels, and each kernel is of size 3x3. Typically, when we define a convolutional layer on the input data, we must specify the `input_shape` parameter, which is a tuple which stores the dimension of the input tensor. For example, if our input image is of shape `(28,28,1)`, as it is the case for the MNIST dataset, we can specify that when we define the first `Conv2D` layer in our network, using the syntax `Conv2D(filters=32, kernel_size=(3,3), input_shape=(28,28,1))`. The input shape parameter is authomatically set of subsequent layers in our network.

**MaxPooling layer:**After adding a convolutional layer, we can typically apply a `MaxPool` layer, to reduce the spatial resolution of the output tensor. The `MaxPool` layer takes as input the `pool_size=(2,2)`.

After we specify the convolutional and max-pooling layer in our architecture, we can then append the necessary dense layer to perform prediction task. The following code illustrates how to define a simple CNN architecture using the above layers.

```python
model= Sequential() 

input_shape = X_train[0].shape

# 32: number of filters, (3,3): kernel_size, input_shape (28,28,1) 
# Output:  #epoch x 26 x 26 x filters ; convolutions reduces image size by kernal-size-1
# #params 3*3*32= 280 + 32 biases. 
model.add(Conv2D(32,(3,3),activation='relu',input_shape=input_shape))

# MaxPool2D Layer -> 
# Output : epoch x 13 x 13 x #fitlers
model.add(MaxPool2D(pool_size=(2,2)))

# Dropout Layer Output epoch x 13 x 13 x #fitlers
model.add(Dropout(0.5))

# parameters : 3*3*32*64=18432 for W, plus 64 biases =  18496 
model.add(Conv2D(64,(3,3),activation='relu'))
 
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.5))


# Flatten tensor epoch x 5408; (13*13*32-filters)
model.add(Flatten())

# Dense Layer Output : epoch x 32
model.add(Dense(32,activation='relu'))

# Dropout layer epoch x 32 
model.add(Dropout(0.5))

# Dense layer : expoch x 10 
model.add(Dense(10,activation='softmax'))


```


**Task 2.1** In the cell below, define the neural network architecture specified in the section above.

In [11]:
# Implement Task 2.1 
model= Sequential() 

input_shape = X_train[0].shape

# 32: number of filters, (3,3): kernel_size, input_shape (28,28,1) 
# Output:  #epoch x 26 x 26 x filters ; convolutions reduces image size by kernal-size-1
# #params 3*3*32= 280 + 32 biases. 
model.add(Conv2D(32,(3,3),activation='relu',input_shape=input_shape))

# MaxPool2D Layer -> 
# Output : epoch x 13 x 13 x #fitlers
model.add(MaxPool2D(pool_size=(2,2)))

# Dropout Layer Output epoch x 13 x 13 x #fitlers
model.add(Dropout(0.5))

# parameters : 3*3*32*64=18432 for W, plus 64 biases =  18496 
model.add(Conv2D(64,(3,3),activation='relu'))

model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.5))


# Flatten tensor epoch x 5408; (13*13*32-filters)
model.add(Flatten())

# Dense Layer Output : epoch x 32
model.add(Dense(32,activation='relu'))

# Dropout layer epoch x 32 
model.add(Dropout(0.5))

# Dense layer : expoch x 10 
model.add(Dense(10,activation='softmax'))


**Compile the Neural Network Architecture**
Once we define the model, we need to compile it using the `model.compile` method of the API. We can train the compiled model  by calling the `model.fit` method of the API. Once we have a trained model, we can evaluate its performance on a test set by using `model.evaluate` method and apply the model to make prediction on new unseen data using the `model.predict` method.

**Task 2.2:** Compile the Neural Network Architecture you defined in task 2.1

**Task 2.3** Train the model by calling the `model.fit` method

**Task 2.4:** Evaluate the model you trained in task 2.3 and report its accuracy and loss.

**Task 2.5** Apply the model you trained in task 2.4 on the test set and report its performance. Moreover, identify the first three instances the model misclassifies and display their image; indicating in the title the predicted value.

Use the cells below to complete these tasks 


In [12]:
#
# Complete task 2.2 here.
#
history = model.compile(optimizer='adam',
             loss = 'categorical_crossentropy',
             metrics = 'accuracy')


In [ ]:
#
# Complete task 2.3 here.
#
model.fit(X_train, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 58s 31ms/step - loss: 0.2320 - accuracy: 0.9243
Epoch 2/5
1875/1875 [==============================] - 58s 31ms/step - loss: 0.2219 - accuracy: 0.9283
Epoch 3/5
1875/1875 [==============================] - 59s 31ms/step - loss: 0.2111 - accuracy: 0.9322
Epoch 4/5
1875/1875 [==============================] - 58s 31ms/step - loss: 0.2036 - accuracy: 0.9334
Epoch 5/5
1875/1875 [==============================] - 58s 31ms/step - loss: 0.1937 - accuracy: 0.9369


In [13]:
#
# Complete task 2.4 here.
#

prob_model = tensorflow.keras.Sequential([model, 
                                         tensorflow.keras.layers.Softmax()])
predictions = prob_model.predict(X_train)
print(predictions)
test_loss, test_acc = model.evaluate(X_train,  y_train, verbose=2)

[[0.10088819 0.10058796 0.09952245 ... 0.10056029 0.10068982 0.09955645]
 [0.09993362 0.1010287  0.09899915 ... 0.10050362 0.10084172 0.09893003]
 [0.09945541 0.10069453 0.09915567 ... 0.10063115 0.10133992 0.09909166]
 ...
 [0.10033536 0.10046516 0.0991651  ... 0.10098004 0.10132959 0.0996418 ]
 [0.1000993  0.10051004 0.09950419 ... 0.10030561 0.10089555 0.09902417]
 [0.09979905 0.10057898 0.09913067 ... 0.10069012 0.10126793 0.09935408]]
1875/1875 - 15s - loss: 2.3053 - accuracy: 0.0772


In [14]:
#
# Complete task 2.5 here.
from sklearn.metrics import classification_report
test_loss, test_acc = model.evaluate(X_train,  y_train, verbose=2)


1875/1875 - 16s - loss: 2.3053 - accuracy: 0.0772


## Exercise 3 Loading your own dataset. 

The code below illustrates how to download a remote dataset, and unzip it. As an example, we use the Cats and Dogs dataset provided by Microsoft and is available at this url https://www.microsoft.com/en-us/download/confirmation.aspx?id=54765  (direct link: https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip) 

You can download the dataset using the `wget` command; and unzip it using the `uzip` command. The code below illustrates how to do this



In [15]:
!wget -O /content/sample_data/CatsAndDogs.zip https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip

--2020-10-21 00:26:53--  https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip
Resolving download.microsoft.com (download.microsoft.com)... 23.34.168.144, 2600:1403:8c00:1a7::e59, 2600:1403:8c00:190::e59, ...
Connecting to download.microsoft.com (download.microsoft.com)|23.34.168.144|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 824894548 (787M) [application/octet-stream]
Saving to: ‘/content/sample_data/CatsAndDogs.zip’

/content/sample_dat 100%[===================>] 786.68M   103MB/s    in 9.1s    

2020-10-21 00:27:03 (86.8 MB/s) - ‘/content/sample_data/CatsAndDogs.zip’ saved [824894548/824894548]



In [ ]:
!unzip /content/sample_data/CatsAndDogs.zip

To preprocess the dataset, we need the following libraries. 

In [17]:
from skimage import io
import os
import numpy as np 
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

A basic pre-processing step we need to apply in new image datasets is to resize them and normalize them. As part of this example, we will pre-process the image by cropping each image to a square; resize it to a requested size; and normalize each image. The function `standarize_image` below does exactly that. You will use this function to pre-process the dataset.

In [18]:
# Takes as input an image-array, resizes the image, and normalizes it. 
def standarize_image(img_array,resize_pixels=256): 
  # Convert array to image; 
  img = Image.fromarray(img_array)

  # Convert image into a square image.
  cols, rows = img.size
  extra = (rows-cols)/2

  if (extra>0):  
    # more rows than columns, crop rows
    crop_box = (0,extra,cols,cols+extra)
  else:
    # more cols than rows, crop cols
    crop_box = (-extra,0,rows-extra,rows) 

  # Crop image into a square and resize image based on resize_pixels
  standarized_image = img.crop(crop_box).resize((resize_pixels,resize_pixels), Image.ANTIALIAS)

  # conver image to vector convert type to float; normalize values between -1 and 1. 
  standarized_image_vector = (np.asarray(standarized_image).flatten().astype(np.float32)-128)/128 

  standarized_image_tensor = (np.asarray(standarized_image).astype(np.float32)-128)/128 

  return standarized_image_tensor, standarized_image_vector, standarized_image


**Load and pre-process the dataset**
The code below illustrates how to load the dataset. 
```python
# Go over the entire dataset and convert it into a single files. 
x_all = []
y_all = []

Categories = ["Cat","Dog"]
sample_size = 100

for category in Categories:     # do dogs and cats
    class_num = Categories.index(category)
    path = os.path.join(data_root_folder,category)  # create path to dogs and cats
   
    image_list = os.listdir(path)
    image_list = image_list[0:sample_size]
    for img in image_list:  # iterate over each image per dogs and cats
      img_array = io.imread(image)  
      (img_tensor,_,img) = standarize_image(img_array,32)
    
      x_all.append(img_tensor)
      y_all.append(class_num)

# Convert the list to a 4D array 
x_all = np.array(x_all)
y_all = np.array(y_all) 
```
**Task 3.1** Reproduce the code above, but change it so that it returns a sample of 4000 images (2000 for each class) of size 64 by 64 pixels each.  

In [68]:
# Implement task 3.1 

x_all = []
y_all = []

Categories = ["Cat", "Dog"]
sample_size = 4000

for category in Categories:
  class_num = Categories.index(category)
  path = os.path.join('/content/PetImages', category)
  image_list = os.listdir(path)
  image_list = image_list[0:sample_size]

  for img in image_list:
      img_array = io.imread(img)
      (img_tensor, _, img) = standarize_image(img_array,64)

      x_all.append(img_tensor)
      y_all.append(class_num)
        

x_all = np.array(x_all)
y_all = np.array(y_all)



FileNotFoundError: ignored

In the steps above, you create a standardized  dataset `x_all` that stores all observations in the dataset, and `y_all` that stores all the corresponding elements in the dataset. To train a model, we need to `slit` the dataset into a train and test set. We can do that using the `train_test_split` method of `sklearn` library as follows :

```python 
(X_train, X_test, y_train, y_test) = train_test_split(x_all, y_all, test_size=0.25, random_state=42)
```
then to store the dataset for further processing, we can use the `save` method provided by numpy as follows: 

```python
dataset = ((X_train, y_train), (X_test, y_test))

# saves data in a file CatDog_preprocessed.npy, under folder sample_data.
np.save('sample_data/CatsDog_preprocessed',dataset)
```

Subsequently, we can load the data in a format we can use in a network; using the following code:
```python
(X_train, y_train), (X_test, y_test) = np.load("sample_data/CatsDog_preprocessed.npy",allow_pickle=True)

```

**Task 3.2:** Use the sample code above to a) split the `x_all` and `y_all` dataset into a `train` and `test` set. Save the resulting slit into a tuple format (similar to the format the MNIST dataset is stored). 

In [ ]:
#
# Task 3.2: Implement the task 3.2 
#
(X_train, X_test, y_train, y_test) = train_test_split(x_all, y_all, test_size=0.25, random_state=42)

dataset = ((X_train, y_train), (X_test, y_test))
# saves data in a file CatDog_preprocessed.npy, under folder sample_data.
np.save('sample_data/CatsDog_preprocessed',dataset)

(X_train, y_train), (X_test, y_test) = np.load("sample_data/CatsDog_preprocessed.npy",allow_pickle=True)

# Exercise 4

Build a convolutional neural network (CNN) to classify images to either `cats` or `dogs` using the Microsoft dataset. Report the network performance and apply the network on the test set. Use as many cells as necessary.


In [42]:
#
# Implement exercise 4; use additional cells as necessary. 
#
import tensorflow.keras 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPool2D, Dropout
import time

model= Sequential() 

input_shape = X_train[0].shape

model.add(Conv2D(32,(3,3),activation='relu',input_shape=input_shape))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.5))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(32,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10,activation='softmax'))


history = model.compile(optimizer='adam',
             loss = 'categorical_crossentropy',
             metrics = 'accuracy')

model.fit(X_train, y_train, epochs = 5)

prob_model = tensorflow.keras.Sequential([model, 
                                         tensorflow.keras.layers.Softmax()])
predictions = prob_model.predict(X_train)
print(predictions)
test_loss, test_acc = model.evaluate(X_train,  y_train, verbose=2)

from sklearn.metrics import classification_report
test_loss, test_acc = model.evaluate(X_train,  y_train, verbose=2)


Epoch 1/5
1875/1875 [==============================] - 56s 30ms/step - loss: 0.6148 - accuracy: 0.7958
Epoch 2/5
1875/1875 [==============================] - 59s 31ms/step - loss: 0.2998 - accuracy: 0.9047
Epoch 3/5
1875/1875 [==============================] - 56s 30ms/step - loss: 0.2487 - accuracy: 0.9215
Epoch 4/5
1875/1875 [==============================] - 58s 31ms/step - loss: 0.2217 - accuracy: 0.9285
Epoch 5/5
1875/1875 [==============================] - 56s 30ms/step - loss: 0.2103 - accuracy: 0.9321
[[0.08549242 0.08549243 0.08549243 ... 0.08549254 0.08549482 0.08558634]
 [0.23196924 0.08533674 0.08533674 ... 0.08533674 0.08533676 0.08533675]
 [0.08533978 0.08533982 0.08533978 ... 0.08533987 0.08533978 0.08536038]
 ...
 [0.08533709 0.08533709 0.08533709 ... 0.08533709 0.08533709 0.08533941]
 [0.08533678 0.08533678 0.08533678 ... 0.08533678 0.08533682 0.08533678]
 [0.08535733 0.08535606 0.08537199 ... 0.0853565  0.23166348 0.0854685 ]]
1875/1875 - 17s - loss: 0.0415 - accuracy

Copyright Statement: Copyright © 2020 Christoforou. The materials provided by the instructor of this course, including this notebook, are for the use of the students enrolled in the course. Materials are presented in an educational context for personal use and study and should not be shared, distributed, disseminated or sold in print — or digitally — outside the course without permission. You may not, nor may you knowingly allow others to reproduce or distribute lecture notes, course materials as well as any of their derivatives without the instructor's express written consent.

In [ ]:
Conv2D()